config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "lists#index"
  get "deleted_lists/deleted_marked"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deleted_lists_controller.rb
class DeletedListsController < ApplicationController

    def deleted_marked
        @marked = List.where(:completed => true).destroy_all
        redirect_to root_path
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
    @list = List.new
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to root_path, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to root_path, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bucket List</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
    
  </div>
<% end %>

app/views/lists/_front_form.html.erb
<%= form_with(model: @list) do |form| %>
  <% if @list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :description %>
  </div>
  <br>
  <div>
    <%= form.submit "Add new bucket wish" %>
    
  </div>
<% end %>

app/views/lists/_index_style.html.erb
<section class="gradient-custom">
 
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
       <div class="d-flex justify-content-center align-items-center">
        <%= image_tag("text.png", width: 400, height: 400) %>
      </div>

        <div class="card">
          <div class="card-body p-5 background border-radius" >
   
            <!-- Tabs navs -->

<%= form_with(model: @list) do |form| %>
  <% if @list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label class="form-label text-header" for="form2">Welcome to your 2023 bucket list!</label>
    <%= form.text_field :description, class: "form-control", placeholder: "Write your wish"  %>
  </div>
    <br>
  <div class="align-btn">
    <%= form.submit "Add wish", class: "btn btn-warning button-align align-btn" %>  
  </div>
<% end %>

<% @lists.each do |list| %>
    <%= render list %>
    <%= form_for(list) do |f| %>
    <%= f.text_field :description, type: "hidden"  %>
    <%= f.check_box :completed, :checked =>true, :style => "visibility: hidden" %>
    <%= f.submit "Achieved!" , class: "btn btn-success" %>
<% end  %>
  <% end %>
            <!-- Tabs content -->
  
  <div class="marg">
   <%= link_to "Delete marked items",  deleted_lists_deleted_marked_path, class:"text-red" %>
   </div>
</section>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
 <div class="tab-content" id="ex1-content">
              <div class="tab-pane fade show active" id="ex1-tabs-1" role="tabpanel"
                aria-labelledby="ex1-tab-1">
                <ul class="list-group mb-0">
                  <li class="list-group-item d-flex align-items-center border-0 mb-2 rounded top"
                    style="background-color: #f4f6f7;">
                  
                 
  <p>
    <% if list.completed %>
     <span class="strike">
    <%=  list.description %>
     <%= button_to "X", list, method: :delete, class: "btn btn-danger align-x" %> 
    </span>

    <% else %>

    <%=  list.description  %>
     <%= button_to "X", list, method: :delete, class: "btn btn-danger align-x" %>
    <%end%>
  </p>
  </li>
</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<div id="lists"class="notification">
  <%= render "index_style" %>
</div>

app/views/lists/new.html.erb
<h1>New wish</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>